#ifndef WMA_H
#define WMA_H

#include <memory>

#include <ink/ink_base.hpp>
#include <ink/InkAssert.h>

#include <wma/core/BuildConfig.hpp>  // generated by CMake (angle-bracket: not in the source tree)
#include "core/Types.hpp"
#include "core/WindowDetails.hpp"
#include "core/WindowFlags.hpp"
#include "exceptions/WMAException.hpp"
#include "input/keyboard/Keys.h"
#include "input/keyboard/KeyAction.hpp"
#include "input/keyboard/KeyboardListener.hpp"
#include "input/mouse/MouseListener.hpp"
#include "input/mouse/MouseAction.hpp"
#include "managers/IWindowManager.hpp"
#include "rendering/SoftwareRenderer.hpp"

//! NOTE: concrete backend headers (SdlWindowManager.hpp, …) are intentionally NOT
//! included here. They pull in backend SDK headers (SDL3, GLFW, Xlib, wayland) and
//! would force every consumer TU to have those on its include path. The factory
//! below is defined inside the compiled library where the private WMA_ENABLE_*
//! build macros and SDK headers are available. Use WMA_HAS_* (from BuildConfig.hpp)
//! for feature detection; include a concrete backend header explicitly only if you
//! need backend-specific API.

#define WMA_MAJOR_VERSION WMA_VERSION_MAJOR
#define WMA_MINOR_VERSION WMA_VERSION_MINOR
#define WMA_PATCH_VERSION WMA_VERSION_PATCH
#define WMA_VERSION ((WMA_MAJOR_VERSION * 10000) + (WMA_MINOR_VERSION * 100) + WMA_PATCH_VERSION)
#define WMA_VERSION_STRING_FULL \
    INK_STR(WMA_MAJOR_VERSION) "." INK_STR(WMA_MINOR_VERSION) "." INK_STR(WMA_PATCH_VERSION)

namespace wma {

    /**
     * @brief Create a window manager for the requested backend and graphics API.
     * @throws WMAException if the backend was not compiled into the library.
     *
     * Availability is decided by what the library was built with, not by the
     * consumer's TU — query isBackendAvailable() first, or use getDefaultBackend().
     */
    [[nodiscard]] std::unique_ptr<IWindowManager> createWindowManager(
        WindowBackend backend,
        const WindowDetails& windowDetails,
        GraphicsAPI graphicsAPI);

    //! The preferred backend compiled into this build (SDL3 on WASM/Android).
    [[nodiscard]] WindowBackend getDefaultBackend();

    //! Whether @p backend was compiled into the library.
    [[nodiscard]] bool isBackendAvailable(WindowBackend backend) noexcept;

    //! Human-readable build summary (version, backends, graphics APIs).
    [[nodiscard]] const char* getLibraryInfo() noexcept;

} // namespace wma

#endif // WMA_H
